version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
stack_name = "line-smart-retail-layer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v0yhyb0zequm"
s3_prefix = "line-smart-retail-layer"
parameter_overrides = "Environment=\"dev\""
