# Stack:UseCase-SmartRegister-Backend
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  UseCase-Register-OSS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
Mappings:
  EnvironmentMap:
    dev:
      LineOAChannelId: xxx
      LIFFChannelId: xxx
      LIFFUrl: https://liff.line.me/xxx-xxx
      PayPayApiKey: xxx
      PayPayApiSecret: xxx
      PayPayApiMerchantId: xxx
      PayPayIsProd: False
      RegisterOrderInfoDBName: RegisterOrderInfoTBL
      RegisterItemInfoDBName: RegisterItemInfoTBL
      RegisterCouponInfoDBName: RegisterCouponInfoTBL
      LINEChannelAccessTokenDBName: LINEChannelAccessTokenTBL
      ConfirmUrlPass: /completed.html
      DetailsPass: /history.html
      PaymentImageUrl: "https://media.istockphoto.com/vectors/cash-register-with-a-paper-check-flat-isolated-vector-id1018485968"
      LayerVersion: 1
      LoggerLevel: DEBUG
      LambdaMemorySize: 128
      # TTL is True:Reservation Data will be deleted at the specified date, False:Data will not be deleted
      TTL: True 
      TTLDay: 1
      # ### ACCESS LOG SETTING ###
      # LogS3Bucket: S3BucketName for AccessLog
      # LogFilePrefix: smart-retail-dev/
      # ### ACCESS LOG SETTING ###
    prod:
      LineOAChannelId: LineOAChannelId
      LIFFChannelId: LIFFChannelId
      LIFFUrl: LIFFUrl
      PayPayApiKey: PayPayApiKey
      PayPayApiSecret: PayPayApiSecret
      PayPayApiMerchantId: PayPayApiMerchantId
      PayPayIsProd: True or False
      RegisterOrderInfoDBName: RegisterOrderInfoDBName
      RegisterItemInfoDBName: RegisterItemInfoDBName
      RegisterCouponInfoDBName: RegisterCouponInfoDBName
      LINEChannelAccessTokenDBName: LINEChannelAccessTokenName
      ConfirmUrlPass: /completed.html
      DetailsPass: /history.html
      PaymentImageUrl: "https://media.istockphoto.com/vectors/cash-register-with-a-paper-check-flat-isolated-vector-id1018485968"
      LayerVersion: LayerVersion
      LoggerLevel: INFO or DEBUG
      LambdaMemorySize: 128 to 10,240
      TTL: False 
      TTLDay: 1
      # ### ACCESS LOG SETTING ###
      # LogS3Bucket: S3BucketName for AccessLog
      # LogFilePrefix: smart-retail/
      # ### ACCESS LOG SETTING ###

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SmartRegister-*:*:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/SmartRegister-*:*"
                  - !GetAtt RegisterItemInfoDB.Arn
                  - !GetAtt RegisterOrderInfoDB.Arn
                  - !GetAtt RegisterCouponInfoDB.Arn
                  - !Sub ${RegisterOrderInfoDB.Arn}/index/*
                  - !Join
                    - ""
                    - - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/
                      - !FindInMap [
                          EnvironmentMap,
                          !Ref Environment,
                          LINEChannelAccessTokenDBName,
                        ]
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: "*"
      RoleName: !Sub "${AWS::StackName}-LambdaRole"

  GetItemInfo:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: get_item_info/
      FunctionName: !Sub SmartRegister-GetItemInfo-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          PAY_PAY_ITEM_INFO_DB: !Ref RegisterItemInfoDB
          PAY_PAY_COUPON_INFO_DB: !Ref RegisterCouponInfoDB
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        GetItemInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_item_info
            Method: get
            RestApiId:
              Ref: SmaRegisterApiGateway

  GetOrderInfo:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: get_order_info/
      FunctionName: !Sub SmartRegister-GetOrderInfo-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          LIFF_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LIFFChannelId]
          PAY_PAY_ORDER_INFO_DB: !Ref RegisterOrderInfoDB
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        GetOrderInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_order_info
            Method: get
            RestApiId:
              Ref: SmaRegisterApiGateway

  PutCartData:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: put_cart_data/
      FunctionName: !Sub SmartRegister-PutCartData-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          LIFF_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LIFFChannelId]
          OA_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LineOAChannelId]
          LIFF_URL: !FindInMap [EnvironmentMap, !Ref Environment, LIFFUrl]
          DETAILS_PASS:
            !FindInMap [EnvironmentMap, !Ref Environment, DetailsPass]
          PAY_PAY_ITEM_INFO_DB: !Ref RegisterItemInfoDB
          PAY_PAY_ORDER_INFO_DB: !Ref RegisterOrderInfoDB
          PAY_PAY_COUPON_INFO_DB: !Ref RegisterCouponInfoDB
          CHANNEL_ACCESS_TOKEN_DB:
            !FindInMap [
              EnvironmentMap,
              !Ref Environment,
              LINEChannelAccessTokenDBName,
            ]
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        PutCartData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /put_cart_data
            Method: post
            RestApiId:
              Ref: SmaRegisterApiGateway

  PaypayRequet:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: put_paypay_request/
      FunctionName: !Sub SmartRegister-PaypayRequest-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          LIFF_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LIFFChannelId]
          LIFF_URL: !FindInMap [EnvironmentMap, !Ref Environment, LIFFUrl]
          PAY_PAY_API_KEY:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiKey]
          PAY_PAY_API_SECRET:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiSecret]
          PAY_PAY_API_MERCHANT_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiMerchantId]
          PAY_PAY_IS_PROD:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayIsProd]
          PAY_PAY_ORDER_INFO_DB: !Ref RegisterOrderInfoDB
          CONFIRM_URL_PASS:
            !FindInMap [EnvironmentMap, !Ref Environment, ConfirmUrlPass]
          PAYMENT_IMG_URL:
            !FindInMap [EnvironmentMap, !Ref Environment, PaymentImageUrl]
          TTL_DAY: !FindInMap [EnvironmentMap, !Ref Environment, TTLDay]
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        PutCartData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /put_paypay_request
            Method: post
            RestApiId:
              Ref: SmaRegisterApiGateway

  PaypayDetail:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: put_paypay_detail/
      FunctionName: !Sub SmartRegister-PaypayDetail-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          OA_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LineOAChannelId]
          LIFF_CHANNEL_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, LIFFChannelId]
          LIFF_URL: !FindInMap [EnvironmentMap, !Ref Environment, LIFFUrl]
          PAY_PAY_API_KEY:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiKey]
          PAY_PAY_API_SECRET:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiSecret]
          PAY_PAY_API_MERCHANT_ID:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayApiMerchantId]
          PAY_PAY_IS_PROD:
            !FindInMap [EnvironmentMap, !Ref Environment, PayPayIsProd]
          PAY_PAY_ORDER_INFO_DB: !Ref RegisterOrderInfoDB
          CHANNEL_ACCESS_TOKEN_DB:
            !FindInMap [
              EnvironmentMap,
              !Ref Environment,
              LINEChannelAccessTokenDBName,
            ]
          DETAILS_PASS:
            !FindInMap [EnvironmentMap, !Ref Environment, DetailsPass]
          TTL_DAY: !FindInMap [EnvironmentMap, !Ref Environment, TTLDay]
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        PutCartData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /put_paypay_detail
            Method: post
            RestApiId:
              Ref: SmaRegisterApiGateway

  GetCouponsInfo:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: get_coupons_info/
      FunctionName: !Sub SmartRegister-GetCouponsInfo-${Environment}
      Description: ""
      Layers:
        - !Join
          - ":"
          - - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer"
            - !ImportValue SmartRegisterLayer
            - !FindInMap [EnvironmentMap, !Ref Environment, LayerVersion]
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          PAY_PAY_COUPON_INFO_DB: !Ref RegisterCouponInfoDB
          LOGGER_LEVEL:
            !FindInMap [EnvironmentMap, !Ref Environment, LoggerLevel]
      Events:
        GetCouponInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_coupons_info
            Method: get
            RestApiId:
              Ref: SmaRegisterApiGateway

  RegisterItemInfoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "barcode"
          AttributeType: S
      TableName:
        !FindInMap [EnvironmentMap, !Ref Environment, RegisterItemInfoDBName]
      KeySchema:
        - AttributeName: "barcode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  RegisterOrderInfoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "orderId"
          AttributeType: S
        - AttributeName: "userId"
          AttributeType: S
      TableName:
        !FindInMap [EnvironmentMap, !Ref Environment, RegisterOrderInfoDBName]
      KeySchema:
        - AttributeName: "orderId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: userId-orderId-index
          KeySchema:
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "orderId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "paidDateTime"
              - "amount"
              - "item"
              - "discountWay"
              - "discountRate"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: "expirationDate"
        Enabled: !FindInMap [EnvironmentMap, !Ref Environment, TTL]

  RegisterCouponInfoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "couponId"
          AttributeType: S
      TableName:
        !FindInMap [EnvironmentMap, !Ref Environment, RegisterCouponInfoDBName]
      KeySchema:
        - AttributeName: "couponId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SmaRegisterApiGateway:
    Properties:
      StageName: !Ref Environment
      OpenApiVersion: 3.0.2
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Origin, Authorization, Accept, X-Requested-With, Content-Type, x-amz-date, X-Amz-Security-Token'"
        AllowMethods: "'GET, POST, OPTIONS'"
    Type: AWS::Serverless::Api
    Tags:
      - Key: "Name"
        Value: "LINE"
      - Key: "App"
        Value: "SmaRegister"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/
  GetItemInfoApi:
    Description: "API Gateway endpoint URL for GetItemInfo function"
    Value: !Sub "https://${SmaRegisterApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/get_item_info/"
  GetItemInfoFunction:
    Description: "GetItemInfo Lambda Function ARN"
    Value: !GetAtt GetItemInfo.Arn
  GetOrderInfoApi:
    Description: "API Gateway endpoint URL for GetOrderInfo function"
    Value: !Sub "https://${SmaRegisterApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/get_order_info/"
  GetOrderInfoFunction:
    Description: "GetOrderInfo Lambda Function ARN"
    Value: !GetAtt GetOrderInfo.Arn
  PutCartDataApi:
    Description: "API Gateway endpoint URL for PutCartData function"
    Value: !Sub "https://${SmaRegisterApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/put_cart_data/"
  PutCartDataFunction:
    Description: "PutCartData Lambda Function ARN"
    Value: !GetAtt PutCartData.Arn
  LineOAChannelId:
    Description: "MessagingAPI LineChannelId"
    Value: !FindInMap [EnvironmentMap, !Ref Environment, LineOAChannelId]
  LIFFChannelId:
    Description: "LIFF ChannelId"
    Value: !FindInMap [EnvironmentMap, !Ref Environment, LIFFChannelId]